
server:
  port: 8088
  servlet:
     context-path: /cmis-main
  http2:
     enabled: true
     
 # 开发 jdbc_config datasource
spring.datasource:
   url: jdbc:oracle:thin:@10.1.108.43:1521:coreuat
   username: cmis
   password: credit2014
   driver-class-name: oracle.jdbc.driver.OracleDriver        

# Hikari will use the above plus the following to setup connection pooling
   type: com.zaxxer.hikari.HikariDataSource
   hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1 from dual


mybatis:
  mapper-locations: classpath:mapper/*/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.cmis.entity  # 注意：对应实体类的路径
  configuration:
     log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #将sql打印到控制台

jedis.pool:
    host: 10.2.108.40
    port: 6379
    config: 
      maxTotal: 100
      maxIdle: 10
      maxWaitMillis: 100000

#pagehelper
pagehelper:
   helperDialect: oracle
   reasonable: true
   supportMethodsArguments: true
   pageSizeZero: true
   params: count=countSql 

#thymeleaf模版配置
# 详细参数参考: org.springframework.boot.autoconfigure.thymeleaf.ThymeleafProperties 类.
spring.thymeleaf:
   #开发时关闭缓存,实现页面热部署
   cache: false
   #content-type: text/html
   
#spring.mvc.view.prefix/spring.mvc.view.suffix 

#热部署生效
spring.devtools.restart:
   enabled: true
#设置重启的目录
   additional-paths: src/main/java/com/cmis
#设置不重启目录或者文件
   exclude: application.yml














